### ISSUE TITLE
Some javascript errors in Mova

### ISSUE THREAD

**Issue by gupta-ankit** [omimo/Mova#1]
When I run the file on my local machine I get the following errors in the chrome console

```
syntax error MS2_8Walk_M_nopos.bvh:1:1
TypeError: frames is undefined figureVis.js:10:4
```

**Comment by omimo** [comment]
Do you see the numbers?

**Comment by omimo** [comment]
If you see the numbers I think that's fine for now. It is because the rest of the visualization scripts are not yet updated to read from the new data structures we have. You can still see some visualizations by going to the Toolbox, Features, and use the drop down under select a joint.
