### ISSUE TITLE
Integrate Annotation Prototype with MOVA

### ISSUE THREAD

**Issue by gupta-ankit** [omimo/Mova#3]

**Comment by gupta-ankit** [comment]
@omimo Currently I have the svg for the annotation tracks as a tab. Can you modify the css to make it appear below the "tabbed-pane"?

I tried to modify it but could not figure out how to do that. So, I did not commit those changes and instead just used a tab for now.

**Comment by omimo** [comment]
I moved the div to the appropriate place, next to the #maintabs and #legends divs. Note that now it has a style in the style.css.

**Comment by omimo** [comment]
By the way, later we should decide (with Sarah), where should the extracted features be: inside the tab on the figure sketch, or below the annotation timeline.
