### ISSUE TITLE
Incorrect number of joints.

### ISSUE THREAD

**Issue by gupta-ankit** [omimo/Mova#4]
@omimo reported this bug
When reading "MS2_8Walk_M_nopos.bvh", the parser identifies only 21 joints. The correct number should be 30.

**Comment by gupta-ankit** [comment]
I found two bugs. First, the parser was just ignoring the end site due to an `if` block in the parseLine function. Second, the logic for identifying an end site was incorrect. As per it, the joints with the string `end` (like RightShould_End) were ignored as end site.

I have now fixed that bug.

@omimo Can you check if it is working properly? If it is, you can close the issue.

Also, I have a question about the channels. Do the channels include numbers for end sites as well. If not, I will have to include code to ignore end sites when reading channels.

**Comment by omimo** [comment]
It seems to be working. I would know for sure once we draw a complete skeleton. For now, I close it!
1. I think the safest way to detect end sites is that they do not have children. 
2. End sites do not have channels associated to them in the frame data. However, when we calculate the skeleton's position we need to consider them and calculate their positions with their offsets.
