### ISSUE TITLE
Implement joint matrix

### ISSUE THREAD

**Issue by gupta-ankit** [omimo/Mova#5]
Create a matrix that contains information about connectivity among joints.
## Implementation

The best way to implement it is to create a map, with each key representing a row and then the value of that row is again a map with each key representing a column

```
map = {
 "a" : {"a": 1, "b": 0, "c": 1},
 "b" : {"a": 0, "b": 1,  "c": 0},
 "c" : {"a": 1, "b": 0, "c": 1}
}
```

**Comment by gupta-ankit** [comment]
@omimo can you check if this is what you had in mind

**Comment by omimo** [comment]
So the initial structure that I was using for skeleton, reading from csv was not a matrix!
It was an array bones, each having two properties: the source and destination joints.

**Comment by omimo** [comment]
So I guess, as by the definition of an skeleton, it has to (also) be accessible by the bones.

**Comment by gupta-ankit** [comment]
OK, do you mean joints? What will that function return -- the name of the connected joints?

**Comment by omimo** [comment]
A bone is what connects two joints. 
So, initially I was wrong that I store the skeleton as a connectivity matrix (that was the case at some point but I had changed it -- sorry).
The skeleton needs to be defined as an array of bones, each storing the index (or key) of the two joints that the bone is connecting.

**Comment by omimo** [comment]
skel[0].a : source joint
skel[0].b : dest joint
...
skel[last bone].a
skel[last bone].b
